# Generated by Django 4.1.8 on 2024-04-22 02:43

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0029_blogdetailpage_location_alter_blogdetailpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "video_embeded",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video_embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Insert a video url here",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                use_json_field=None,
            ),
        ),
    ]
