# Generated by Django 4.1.8 on 2024-04-23 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_alter_blogdetailpage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogdetailpage",
            old_name="body",
            new_name="Videos",
        ),
    ]
