# Generated by Django 4.1.8 on 2024-04-23 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0031_rename_body_blogdetailpage_videos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogdetailpage",
            old_name="Videos",
            new_name="body",
        ),
    ]
