# Generated by Django 4.1.8 on 2024-04-23 15:43

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtailvideos.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0032_rename_videos_blogdetailpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetailpage",
            name="videos_here",
            field=wagtail.fields.StreamField(
                [
                    ("video", wagtailvideos.blocks.VideoChooserBlock()),
                    (
                        "video_embeded",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video_embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Insert a video url here",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
        migrations.AlterField(
            model_name="blogdetailpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
