# Generated by Django 4.1.8 on 2024-04-23 15:50

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtailvideos.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0033_blogdetailpage_videos_here_alter_blogdetailpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogdetailpage",
            name="video",
        ),
        migrations.AlterField(
            model_name="blogdetailpage",
            name="videos_here",
            field=wagtail.fields.StreamField(
                [
                    (
                        "upload_video",
                        wagtailvideos.blocks.VideoChooserBlock(required=False),
                    ),
                    (
                        "embed_video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video_embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Insert a video url here",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
    ]
